config/routes.rb
Rails.application.routes.draw do
  resources :bibliotecas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biblioteca.rb
class Biblioteca < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bibliotecas_controller.rb
class BibliotecasController < ApplicationController
  before_action :set_biblioteca, only: [:show, :edit, :update, :destroy]

  # GET /bibliotecas
  # GET /bibliotecas.json
  def index
    @bibliotecas = Biblioteca.all
    if params[:ordenar]=='titulo'
      @bibliotecas = Biblioteca.all.order('titulo')
    elsif params[:ordenar]=='estado'
      @bibliotecas = Biblioteca.all.order('estado')
    end
end

  # GET /bibliotecas/1
  # GET /bibliotecas/1.json
  def show
  end

  # GET /bibliotecas/new
  def new
    @biblioteca = Biblioteca.new
  end

  # GET /bibliotecas/1/edit
  def edit
  end

  # POST /bibliotecas
  # POST /bibliotecas.json
  def create
    @biblioteca = Biblioteca.new(biblioteca_params)

    respond_to do |format|
      if @biblioteca.save
        format.html { redirect_to @biblioteca, notice: 'Biblioteca was successfully created.' }
        format.json { render :show, status: :created, location: @biblioteca }
      else
        format.html { render :new }
        format.json { render json: @biblioteca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bibliotecas/1
  # PATCH/PUT /bibliotecas/1.json
  def update
    respond_to do |format|
      if @biblioteca.update(biblioteca_params)
        format.html { redirect_to @biblioteca, notice: 'Biblioteca was successfully updated.' }
        format.json { render :show, status: :ok, location: @biblioteca }
      else
        format.html { render :edit }
        format.json { render json: @biblioteca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bibliotecas/1
  # DELETE /bibliotecas/1.json
  def destroy
    @biblioteca.destroy
    respond_to do |format|
      format.html { redirect_to bibliotecas_url, notice: 'Biblioteca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biblioteca
      @biblioteca = Biblioteca.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def biblioteca_params
      params.require(:biblioteca).permit(:titulo, :autor, :estado, :fecha_prestado, :fecha_devolucion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bibliotecas_helper.rb
module BibliotecasHelper
end

app/views/bibliotecas/_form.html.erb
<%= form_with(model: biblioteca, local: true) do |form| %>
  <% if biblioteca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(biblioteca.errors.count, "error") %> prohibited this biblioteca from being saved:</h2>

      <ul>
      <% biblioteca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :autor %>
    <%= form.text_field :autor %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.check_box :estado %>
  </div>

  <div class="field">
    <%= form.label :fecha_prestado %>
    <%= form.datetime_select :fecha_prestado %>
  </div>

  <div class="field">
    <%= form.label :fecha_devolucion %>
    <%= form.datetime_select :fecha_devolucion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bibliotecas/edit.html.erb
<h1>Editing Biblioteca</h1>

<%= render 'form', biblioteca: @biblioteca %>

<%= link_to 'Show', @biblioteca %> |
<%= link_to 'Back', bibliotecas_path %>

app/views/bibliotecas/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'titulo', bibliotecas_path(ordenar:'titulo') %>
<%= link_to 'estado', bibliotecas_path(ordenar:'estado') %>
<h1>Bibliotecas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Autor</th>
      <th>Estado</th>
      <th>Fecha prestado</th>
      <th>Fecha devolucion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bibliotecas.each do |biblioteca| %>
      <tr>
        <td><%= biblioteca.titulo %></td>
        <td><%= biblioteca.autor %></td>
        <td><%= biblioteca.estado %></td>
        <td><%= biblioteca.fecha_prestado %></td>
        <td><%= biblioteca.fecha_devolucion %></td>
        <td><%= link_to 'Show', biblioteca %></td>
        <td><%= link_to 'Edit', edit_biblioteca_path(biblioteca) %></td>
        <td><%= link_to 'Destroy', biblioteca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Biblioteca', new_biblioteca_path %>

app/views/bibliotecas/new.html.erb
<h1>New Biblioteca</h1>

<%= render 'form', biblioteca: @biblioteca %>

<%= link_to 'Back', bibliotecas_path %>

app/views/bibliotecas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @biblioteca.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @biblioteca.autor %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @biblioteca.estado %>
</p>

<p>
  <strong>Fecha prestado:</strong>
  <%= @biblioteca.fecha_prestado %>
</p>

<p>
  <strong>Fecha devolucion:</strong>
  <%= @biblioteca.fecha_devolucion %>
</p>

<%= link_to 'Edit', edit_biblioteca_path(@biblioteca) %> |
<%= link_to 'Back', bibliotecas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>